spring:
  datasource:
    url: jdbc:mysql://47.109.51.81:3306/powerdealer?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: powerdealer213

server:
  port: 3579
  address: 0.0.0.0
  tomcat:
    uri-encoding: UTF-8

